### ISSUE TITLE
Udvikles der på dette projekt ?

### ISSUE THREAD

**Issue by mikkeljohnsen** [digst/OIOIDWS.Net#1]
Er der udvikling på dette projekt ?

Skal man bruge noget andet OIOSAML.NET ?
eller Seal.net ?

Hvad er forskellen på de 3 ?

Jeg synes det er en rode butik og der er ingen ordentlige eksempler andet en web test, med alt config i XML filer og intet er opdateret til SHA256 i test.

Det er meget frustrerende.

**Comment by useerup** [comment]
OIOIDWS.Net kan du bruge, hvis du skal implementere en .NET baseret aftager eller udbyder af en identitetsbaseret webservice. Eksemplerne viser både hvordan aftagere og udbydere kan implementeres.

I visse tilfælde vil du også bruge OIOSAML.Net. OIOSAML.Net har til formål at integrere til NemLog-in. Hvis du kun skal integrere med login-funktionaliteten i NemLog-in skal du ikke bruge OIOIDWS.Net.

Hvis du fx laver et website til en offentlig myndighed som skal understøtte single-signon gennem NemLog-in og som skal kalde en webservice som kræver et identitetsbaseret token, så kan du bruge bootstrap eksemplet. I Dette eksempel illustrerer hvordan du kan hente bootstrap token ud af det token som du får fra NemLog-in ved single-signon (her bruger du OIOSAML.Net), og hvordan du så kan veksle dette token til et webservice-specifikt token gennem NemLog-ins STS (her bruger du OIOIDWS.Net) og kalder webservicen med det specifikke webservice-token (her bruger du så også OIOIDWS).

Her i kildekoden er alle udløbne certifikater nu fornyet og referencer til thumbprints er opdateret i konfiguration og eksempel kode. Alle digest burde nu være SHA256.

Der er på dette tidspunkt ikke dannet nye Nuget pakker. Hold eventuelt øje med Nuget. De nye pakker vil bliver versioneret 3.1.0

**Comment by mdbech** [comment]
@mikkeljohnsen: Version 3.1.0 som @useerup nævner er frigivet og er beskrevet på https://www.digitaliser.dk/news/6072495

SHA256 benyttes som @useerup beskriver af NemLog-in IdP og STS i dag så det kan meget vel tænkes at det beror på en misforståelse.

Da dette issue ikke indeholder nogen problemer og alle spørgsmål er blevet besvaret lukker jeg det.
